// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RemotingCommand1.proto

package com.my.mq.serializer.protobuf;

public final class RemotingCommand1 {
  private RemotingCommand1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Command)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 code = 1;</code>
     */
    int getCode();

    /**
     * <code>int32 version = 2;</code>
     */
    int getVersion();

    /**
     * <code>string remark = 3;</code>
     */
    String getRemark();
    /**
     * <code>string remark = 3;</code>
     */
    com.google.protobuf.ByteString
        getRemarkBytes();

    /**
     * <code>map&lt;string, string&gt; extFields = 4;</code>
     */
    int getExtFieldsCount();
    /**
     * <code>map&lt;string, string&gt; extFields = 4;</code>
     */
    boolean containsExtFields(
            String key);
    /**
     * Use {@link #getExtFieldsMap()} instead.
     */
    @Deprecated
    java.util.Map<String, String>
    getExtFields();
    /**
     * <code>map&lt;string, string&gt; extFields = 4;</code>
     */
    java.util.Map<String, String>
    getExtFieldsMap();
    /**
     * <code>map&lt;string, string&gt; extFields = 4;</code>
     */

    String getExtFieldsOrDefault(
            String key,
            String defaultValue);
    /**
     * <code>map&lt;string, string&gt; extFields = 4;</code>
     */

    String getExtFieldsOrThrow(
            String key);

    /**
     * <code>int32 requestId = 5;</code>
     */
    int getRequestId();

    /**
     * <code>.Command.LanguageCode language = 6;</code>
     */
    int getLanguageValue();
    /**
     * <code>.Command.LanguageCode language = 6;</code>
     */
    Command.LanguageCode getLanguage();

    /**
     * <code>.Command.SerializeType serializeType = 7;</code>
     */
    int getSerializeTypeValue();
    /**
     * <code>.Command.SerializeType serializeType = 7;</code>
     */
    Command.SerializeType getSerializeType();

    /**
     * <code>.Command.RemotingCommandType remotingCommandType = 8;</code>
     */
    int getRemotingCommandTypeValue();
    /**
     * <code>.Command.RemotingCommandType remotingCommandType = 8;</code>
     */
    Command.RemotingCommandType getRemotingCommandType();

    /**
     * <code>bytes body = 9;</code>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code Command}
   */
  public  static final class Command extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Command)
      CommandOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Command.newBuilder() to construct.
    private Command(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Command() {
      remark_ = "";
      language_ = 0;
      serializeType_ = 0;
      remotingCommandType_ = 0;
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Command(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 16: {

              version_ = input.readInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              remark_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                extFields_ = com.google.protobuf.MapField.newMapField(
                    ExtFieldsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000008;
              }
              com.google.protobuf.MapEntry<String, String>
              extFields__ = input.readMessage(
                  ExtFieldsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              extFields_.getMutableMap().put(
                  extFields__.getKey(), extFields__.getValue());
              break;
            }
            case 40: {

              requestId_ = input.readInt32();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              language_ = rawValue;
              break;
            }
            case 56: {
              int rawValue = input.readEnum();

              serializeType_ = rawValue;
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              remotingCommandType_ = rawValue;
              break;
            }
            case 74: {

              body_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.rocketmq.remoting.protocol.RemotingCommand1.internal_static_Command_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetExtFields();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.rocketmq.remoting.protocol.RemotingCommand1.internal_static_Command_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Command.class, Builder.class);
    }

    /**
     * Protobuf enum {@code Command.LanguageCode}
     */
    public enum LanguageCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>JAVA = 0;</code>
       */
      JAVA(0),
      /**
       * <code>CPP = 1;</code>
       */
      CPP(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>JAVA = 0;</code>
       */
      public static final int JAVA_VALUE = 0;
      /**
       * <code>CPP = 1;</code>
       */
      public static final int CPP_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static LanguageCode valueOf(int value) {
        return forNumber(value);
      }

      public static LanguageCode forNumber(int value) {
        switch (value) {
          case 0: return JAVA;
          case 1: return CPP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<LanguageCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          LanguageCode> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<LanguageCode>() {
              public LanguageCode findValueByNumber(int number) {
                return LanguageCode.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Command.getDescriptor().getEnumTypes().get(0);
      }

      private static final LanguageCode[] VALUES = values();

      public static LanguageCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private LanguageCode(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Command.LanguageCode)
    }

    /**
     * Protobuf enum {@code Command.SerializeType}
     */
    public enum SerializeType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>JSON = 0;</code>
       */
      JSON(0),
      /**
       * <code>MYMQ = 1;</code>
       */
      MYMQ(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>JSON = 0;</code>
       */
      public static final int JSON_VALUE = 0;
      /**
       * <code>MYMQ = 1;</code>
       */
      public static final int MYMQ_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static SerializeType valueOf(int value) {
        return forNumber(value);
      }

      public static SerializeType forNumber(int value) {
        switch (value) {
          case 0: return JSON;
          case 1: return MYMQ;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<SerializeType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          SerializeType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SerializeType>() {
              public SerializeType findValueByNumber(int number) {
                return SerializeType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Command.getDescriptor().getEnumTypes().get(1);
      }

      private static final SerializeType[] VALUES = values();

      public static SerializeType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private SerializeType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Command.SerializeType)
    }

    /**
     * Protobuf enum {@code Command.RemotingCommandType}
     */
    public enum RemotingCommandType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>REQUEST_COMMAND = 0;</code>
       */
      REQUEST_COMMAND(0),
      /**
       * <code>RESPONSE_COMMAND = 1;</code>
       */
      RESPONSE_COMMAND(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>REQUEST_COMMAND = 0;</code>
       */
      public static final int REQUEST_COMMAND_VALUE = 0;
      /**
       * <code>RESPONSE_COMMAND = 1;</code>
       */
      public static final int RESPONSE_COMMAND_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static RemotingCommandType valueOf(int value) {
        return forNumber(value);
      }

      public static RemotingCommandType forNumber(int value) {
        switch (value) {
          case 0: return REQUEST_COMMAND;
          case 1: return RESPONSE_COMMAND;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RemotingCommandType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          RemotingCommandType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RemotingCommandType>() {
              public RemotingCommandType findValueByNumber(int number) {
                return RemotingCommandType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Command.getDescriptor().getEnumTypes().get(2);
      }

      private static final RemotingCommandType[] VALUES = values();

      public static RemotingCommandType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private RemotingCommandType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Command.RemotingCommandType)
    }

    private int bitField0_;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private int version_;
    /**
     * <code>int32 version = 2;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int REMARK_FIELD_NUMBER = 3;
    private volatile Object remark_;
    /**
     * <code>string remark = 3;</code>
     */
    public String getRemark() {
      Object ref = remark_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        remark_ = s;
        return s;
      }
    }
    /**
     * <code>string remark = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRemarkBytes() {
      Object ref = remark_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        remark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTFIELDS_FIELD_NUMBER = 4;
    private static final class ExtFieldsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, String> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, String>newDefaultInstance(
                  org.apache.rocketmq.remoting.protocol.RemotingCommand1.internal_static_Command_ExtFieldsEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        String, String> extFields_;
    private com.google.protobuf.MapField<String, String>
    internalGetExtFields() {
      if (extFields_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ExtFieldsDefaultEntryHolder.defaultEntry);
      }
      return extFields_;
    }

    public int getExtFieldsCount() {
      return internalGetExtFields().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; extFields = 4;</code>
     */

    public boolean containsExtFields(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetExtFields().getMap().containsKey(key);
    }
    /**
     * Use {@link #getExtFieldsMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, String> getExtFields() {
      return getExtFieldsMap();
    }
    /**
     * <code>map&lt;string, string&gt; extFields = 4;</code>
     */

    public java.util.Map<String, String> getExtFieldsMap() {
      return internalGetExtFields().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; extFields = 4;</code>
     */

    public String getExtFieldsOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetExtFields().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; extFields = 4;</code>
     */

    public String getExtFieldsOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetExtFields().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int REQUESTID_FIELD_NUMBER = 5;
    private int requestId_;
    /**
     * <code>int32 requestId = 5;</code>
     */
    public int getRequestId() {
      return requestId_;
    }

    public static final int LANGUAGE_FIELD_NUMBER = 6;
    private int language_;
    /**
     * <code>.Command.LanguageCode language = 6;</code>
     */
    public int getLanguageValue() {
      return language_;
    }
    /**
     * <code>.Command.LanguageCode language = 6;</code>
     */
    public LanguageCode getLanguage() {
      @SuppressWarnings("deprecation")
      LanguageCode result = LanguageCode.valueOf(language_);
      return result == null ? LanguageCode.UNRECOGNIZED : result;
    }

    public static final int SERIALIZETYPE_FIELD_NUMBER = 7;
    private int serializeType_;
    /**
     * <code>.Command.SerializeType serializeType = 7;</code>
     */
    public int getSerializeTypeValue() {
      return serializeType_;
    }
    /**
     * <code>.Command.SerializeType serializeType = 7;</code>
     */
    public SerializeType getSerializeType() {
      @SuppressWarnings("deprecation")
      SerializeType result = SerializeType.valueOf(serializeType_);
      return result == null ? SerializeType.UNRECOGNIZED : result;
    }

    public static final int REMOTINGCOMMANDTYPE_FIELD_NUMBER = 8;
    private int remotingCommandType_;
    /**
     * <code>.Command.RemotingCommandType remotingCommandType = 8;</code>
     */
    public int getRemotingCommandTypeValue() {
      return remotingCommandType_;
    }
    /**
     * <code>.Command.RemotingCommandType remotingCommandType = 8;</code>
     */
    public RemotingCommandType getRemotingCommandType() {
      @SuppressWarnings("deprecation")
      RemotingCommandType result = RemotingCommandType.valueOf(remotingCommandType_);
      return result == null ? RemotingCommandType.UNRECOGNIZED : result;
    }

    public static final int BODY_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>bytes body = 9;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (version_ != 0) {
        output.writeInt32(2, version_);
      }
      if (!getRemarkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, remark_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetExtFields(),
          ExtFieldsDefaultEntryHolder.defaultEntry,
          4);
      if (requestId_ != 0) {
        output.writeInt32(5, requestId_);
      }
      if (language_ != LanguageCode.JAVA.getNumber()) {
        output.writeEnum(6, language_);
      }
      if (serializeType_ != SerializeType.JSON.getNumber()) {
        output.writeEnum(7, serializeType_);
      }
      if (remotingCommandType_ != RemotingCommandType.REQUEST_COMMAND.getNumber()) {
        output.writeEnum(8, remotingCommandType_);
      }
      if (!body_.isEmpty()) {
        output.writeBytes(9, body_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, version_);
      }
      if (!getRemarkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, remark_);
      }
      for (java.util.Map.Entry<String, String> entry
           : internalGetExtFields().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, String>
        extFields__ = ExtFieldsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, extFields__);
      }
      if (requestId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, requestId_);
      }
      if (language_ != LanguageCode.JAVA.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, language_);
      }
      if (serializeType_ != SerializeType.JSON.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, serializeType_);
      }
      if (remotingCommandType_ != RemotingCommandType.REQUEST_COMMAND.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, remotingCommandType_);
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Command)) {
        return super.equals(obj);
      }
      Command other = (Command) obj;

      if (getCode()
          != other.getCode()) return false;
      if (getVersion()
          != other.getVersion()) return false;
      if (!getRemark()
          .equals(other.getRemark())) return false;
      if (!internalGetExtFields().equals(
          other.internalGetExtFields())) return false;
      if (getRequestId()
          != other.getRequestId()) return false;
      if (language_ != other.language_) return false;
      if (serializeType_ != other.serializeType_) return false;
      if (remotingCommandType_ != other.remotingCommandType_) return false;
      if (!getBody()
          .equals(other.getBody())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + REMARK_FIELD_NUMBER;
      hash = (53 * hash) + getRemark().hashCode();
      if (!internalGetExtFields().getMap().isEmpty()) {
        hash = (37 * hash) + EXTFIELDS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetExtFields().hashCode();
      }
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId();
      hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
      hash = (53 * hash) + language_;
      hash = (37 * hash) + SERIALIZETYPE_FIELD_NUMBER;
      hash = (53 * hash) + serializeType_;
      hash = (37 * hash) + REMOTINGCOMMANDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + remotingCommandType_;
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Command parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Command parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Command prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Command}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Command)
        CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.rocketmq.remoting.protocol.RemotingCommand1.internal_static_Command_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetExtFields();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableExtFields();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.rocketmq.remoting.protocol.RemotingCommand1.internal_static_Command_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Command.class, Builder.class);
      }

      // Construct using org.apache.rocketmq.remoting.protocol.RemotingCommand1.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        version_ = 0;

        remark_ = "";

        internalGetMutableExtFields().clear();
        requestId_ = 0;

        language_ = 0;

        serializeType_ = 0;

        remotingCommandType_ = 0;

        body_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.rocketmq.remoting.protocol.RemotingCommand1.internal_static_Command_descriptor;
      }

      @Override
      public Command getDefaultInstanceForType() {
        return Command.getDefaultInstance();
      }

      @Override
      public Command build() {
        Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Command buildPartial() {
        Command result = new Command(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.code_ = code_;
        result.version_ = version_;
        result.remark_ = remark_;
        result.extFields_ = internalGetExtFields();
        result.extFields_.makeImmutable();
        result.requestId_ = requestId_;
        result.language_ = language_;
        result.serializeType_ = serializeType_;
        result.remotingCommandType_ = remotingCommandType_;
        result.body_ = body_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Command) {
          return mergeFrom((Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Command other) {
        if (other == Command.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (!other.getRemark().isEmpty()) {
          remark_ = other.remark_;
          onChanged();
        }
        internalGetMutableExtFields().mergeFrom(
            other.internalGetExtFields());
        if (other.getRequestId() != 0) {
          setRequestId(other.getRequestId());
        }
        if (other.language_ != 0) {
          setLanguageValue(other.getLanguageValue());
        }
        if (other.serializeType_ != 0) {
          setSerializeTypeValue(other.getSerializeTypeValue());
        }
        if (other.remotingCommandType_ != 0) {
          setRemotingCommandTypeValue(other.getRemotingCommandTypeValue());
        }
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Command parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Command) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int code_ ;
      /**
       * <code>int32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 1;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 1;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>int32 version = 2;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>int32 version = 2;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 version = 2;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private Object remark_ = "";
      /**
       * <code>string remark = 3;</code>
       */
      public String getRemark() {
        Object ref = remark_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          remark_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string remark = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRemarkBytes() {
        Object ref = remark_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          remark_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string remark = 3;</code>
       */
      public Builder setRemark(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        remark_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string remark = 3;</code>
       */
      public Builder clearRemark() {
        
        remark_ = getDefaultInstance().getRemark();
        onChanged();
        return this;
      }
      /**
       * <code>string remark = 3;</code>
       */
      public Builder setRemarkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        remark_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          String, String> extFields_;
      private com.google.protobuf.MapField<String, String>
      internalGetExtFields() {
        if (extFields_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ExtFieldsDefaultEntryHolder.defaultEntry);
        }
        return extFields_;
      }
      private com.google.protobuf.MapField<String, String>
      internalGetMutableExtFields() {
        onChanged();;
        if (extFields_ == null) {
          extFields_ = com.google.protobuf.MapField.newMapField(
              ExtFieldsDefaultEntryHolder.defaultEntry);
        }
        if (!extFields_.isMutable()) {
          extFields_ = extFields_.copy();
        }
        return extFields_;
      }

      public int getExtFieldsCount() {
        return internalGetExtFields().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; extFields = 4;</code>
       */

      public boolean containsExtFields(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetExtFields().getMap().containsKey(key);
      }
      /**
       * Use {@link #getExtFieldsMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, String> getExtFields() {
        return getExtFieldsMap();
      }
      /**
       * <code>map&lt;string, string&gt; extFields = 4;</code>
       */

      public java.util.Map<String, String> getExtFieldsMap() {
        return internalGetExtFields().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; extFields = 4;</code>
       */

      public String getExtFieldsOrDefault(
          String key,
          String defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetExtFields().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; extFields = 4;</code>
       */

      public String getExtFieldsOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetExtFields().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearExtFields() {
        internalGetMutableExtFields().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; extFields = 4;</code>
       */

      public Builder removeExtFields(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableExtFields().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, String>
      getMutableExtFields() {
        return internalGetMutableExtFields().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; extFields = 4;</code>
       */
      public Builder putExtFields(
          String key,
          String value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableExtFields().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; extFields = 4;</code>
       */

      public Builder putAllExtFields(
          java.util.Map<String, String> values) {
        internalGetMutableExtFields().getMutableMap()
            .putAll(values);
        return this;
      }

      private int requestId_ ;
      /**
       * <code>int32 requestId = 5;</code>
       */
      public int getRequestId() {
        return requestId_;
      }
      /**
       * <code>int32 requestId = 5;</code>
       */
      public Builder setRequestId(int value) {
        
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 requestId = 5;</code>
       */
      public Builder clearRequestId() {
        
        requestId_ = 0;
        onChanged();
        return this;
      }

      private int language_ = 0;
      /**
       * <code>.Command.LanguageCode language = 6;</code>
       */
      public int getLanguageValue() {
        return language_;
      }
      /**
       * <code>.Command.LanguageCode language = 6;</code>
       */
      public Builder setLanguageValue(int value) {
        language_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Command.LanguageCode language = 6;</code>
       */
      public LanguageCode getLanguage() {
        @SuppressWarnings("deprecation")
        LanguageCode result = LanguageCode.valueOf(language_);
        return result == null ? LanguageCode.UNRECOGNIZED : result;
      }
      /**
       * <code>.Command.LanguageCode language = 6;</code>
       */
      public Builder setLanguage(LanguageCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        language_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Command.LanguageCode language = 6;</code>
       */
      public Builder clearLanguage() {
        
        language_ = 0;
        onChanged();
        return this;
      }

      private int serializeType_ = 0;
      /**
       * <code>.Command.SerializeType serializeType = 7;</code>
       */
      public int getSerializeTypeValue() {
        return serializeType_;
      }
      /**
       * <code>.Command.SerializeType serializeType = 7;</code>
       */
      public Builder setSerializeTypeValue(int value) {
        serializeType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Command.SerializeType serializeType = 7;</code>
       */
      public SerializeType getSerializeType() {
        @SuppressWarnings("deprecation")
        SerializeType result = SerializeType.valueOf(serializeType_);
        return result == null ? SerializeType.UNRECOGNIZED : result;
      }
      /**
       * <code>.Command.SerializeType serializeType = 7;</code>
       */
      public Builder setSerializeType(SerializeType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        serializeType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Command.SerializeType serializeType = 7;</code>
       */
      public Builder clearSerializeType() {
        
        serializeType_ = 0;
        onChanged();
        return this;
      }

      private int remotingCommandType_ = 0;
      /**
       * <code>.Command.RemotingCommandType remotingCommandType = 8;</code>
       */
      public int getRemotingCommandTypeValue() {
        return remotingCommandType_;
      }
      /**
       * <code>.Command.RemotingCommandType remotingCommandType = 8;</code>
       */
      public Builder setRemotingCommandTypeValue(int value) {
        remotingCommandType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Command.RemotingCommandType remotingCommandType = 8;</code>
       */
      public RemotingCommandType getRemotingCommandType() {
        @SuppressWarnings("deprecation")
        RemotingCommandType result = RemotingCommandType.valueOf(remotingCommandType_);
        return result == null ? RemotingCommandType.UNRECOGNIZED : result;
      }
      /**
       * <code>.Command.RemotingCommandType remotingCommandType = 8;</code>
       */
      public Builder setRemotingCommandType(RemotingCommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        remotingCommandType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Command.RemotingCommandType remotingCommandType = 8;</code>
       */
      public Builder clearRemotingCommandType() {
        
        remotingCommandType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes body = 9;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>bytes body = 9;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes body = 9;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Command)
    }

    // @@protoc_insertion_point(class_scope:Command)
    private static final Command DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Command();
    }

    public static Command getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Command>
        PARSER = new com.google.protobuf.AbstractParser<Command>() {
      @Override
      public Command parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Command(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Command> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Command> getParserForType() {
      return PARSER;
    }

    @Override
    public Command getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Command_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Command_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Command_ExtFieldsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Command_ExtFieldsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026RemotingCommand1.proto\"\324\003\n\007Command\022\014\n\004" +
      "code\030\001 \001(\005\022\017\n\007version\030\002 \001(\005\022\016\n\006remark\030\003 " +
      "\001(\t\022*\n\textFields\030\004 \003(\0132\027.Command.ExtFiel" +
      "dsEntry\022\021\n\trequestId\030\005 \001(\005\022\'\n\010language\030\006" +
      " \001(\0162\025.Command.LanguageCode\022-\n\rserialize" +
      "Type\030\007 \001(\0162\026.Command.SerializeType\0229\n\023re" +
      "motingCommandType\030\010 \001(\0162\034.Command.Remoti" +
      "ngCommandType\022\014\n\004body\030\t \001(\014\0320\n\016ExtFields" +
      "Entry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"!\n" +
      "\014LanguageCode\022\010\n\004JAVA\020\000\022\007\n\003CPP\020\001\"#\n\rSeri" +
      "alizeType\022\010\n\004JSON\020\000\022\010\n\004MYMQ\020\001\"@\n\023Remotin" +
      "gCommandType\022\023\n\017REQUEST_COMMAND\020\000\022\024\n\020RES" +
      "PONSE_COMMAND\020\001B9\n%org.apache.rocketmq.r" +
      "emoting.protocolB\020RemotingCommand1b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Command_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Command_descriptor,
        new String[] { "Code", "Version", "Remark", "ExtFields", "RequestId", "Language", "SerializeType", "RemotingCommandType", "Body", });
    internal_static_Command_ExtFieldsEntry_descriptor =
      internal_static_Command_descriptor.getNestedTypes().get(0);
    internal_static_Command_ExtFieldsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Command_ExtFieldsEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
